import jsPDF from "jspdf";
import { WeeklyPlan } from "./ai/planner.server";

export const exportWeeklyPlanToPDF = (plan: WeeklyPlan) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  const addText = (text: string, x: number, y: number, options: any = {}) => {
    doc.setFontSize(options.fontSize || 12);
    doc.setTextColor(options.color || "#000000");
    doc.text(text, x, y);
  };

  const addHeader = () => {
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, pageWidth, 30, "F");

    addText("Weekly Teaching Plan", pageWidth / 2, 20, {
      fontSize: 20,
      color: "#ffffff",
      align: "center",
    });

    doc.setTextColor("#ffffff");
    doc.setFontSize(12);
    doc.text("Generated by Vidyapak", pageWidth / 2, 25, { align: "center" });

    yPosition = 40;
  };

  const addDaySection = (day: any, dayIndex: number) => {
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = 20;
    }

    const dayColors = {
      Monday: [59, 130, 246],
      Tuesday: [34, 197, 94],
      Wednesday: [234, 179, 8],
      Thursday: [168, 85, 247],
      Friday: [236, 72, 153],
      Saturday: [99, 102, 241],
      Sunday: [249, 115, 22],
    };

    const color = dayColors[day.day as keyof typeof dayColors] || [
      107, 114, 128,
    ];

    doc.setFillColor(color[0], color[1], color[2]);
    doc.rect(15, yPosition, pageWidth - 30, 25, "F");

    addText(day.day, 20, yPosition + 15, {
      fontSize: 16,
      color: "#ffffff",
    });

    yPosition += 35;

    addText("Topics to Teach:", 20, yPosition, {
      fontSize: 12,
      color: "#374151",
    });
    yPosition += 10;

    day.topics.forEach((topic: string, topicIndex: number) => {
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFillColor(255, 255, 255);
      doc.rect(20, yPosition - 5, pageWidth - 40, 12, "F");
      doc.setDrawColor(209, 213, 219);
      doc.rect(20, yPosition - 5, pageWidth - 40, 12, "S");

      addText(`• ${topic}`, 25, yPosition + 2, {
        fontSize: 10,
        color: "#374151",
      });
      yPosition += 15;
    });

    yPosition += 5;
    addText("Homework:", 20, yPosition, { fontSize: 12, color: "#374151" });
    yPosition += 10;

    if (yPosition > pageHeight - 20) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFillColor(255, 255, 255);
    doc.rect(20, yPosition - 5, pageWidth - 40, 12, "F");
    doc.setDrawColor(34, 197, 94);
    doc.rect(20, yPosition - 5, pageWidth - 40, 12, "S");

    const homeworkLines = doc.splitTextToSize(day.homework, pageWidth - 50);
    addText(homeworkLines[0], 25, yPosition + 2, {
      fontSize: 10,
      color: "#374151",
    });

    if (homeworkLines.length > 1) {
      yPosition += 10;
      addText(homeworkLines[1], 25, yPosition + 2, {
        fontSize: 10,
        color: "#374151",
      });
    }

    yPosition += 25;
  };

  const addFooter = () => {
    const footerY = pageHeight - 15;
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text(
      "Generated by Vidyapak - AI Teaching Assistant",
      pageWidth / 2,
      footerY,
      { align: "center" }
    );

    const currentDate = new Date().toLocaleDateString();
    doc.text(`Generated on: ${currentDate}`, pageWidth / 2, footerY + 5, {
      align: "center",
    });
  };

  addHeader();

  plan.days.forEach((day, index) => {
    addDaySection(day, index);
  });

  addFooter();

  const fileName = `Weekly_Teaching_Plan_${
    new Date().toISOString().split("T")[0]
  }.pdf`;
  doc.save(fileName);
};
